// ============================================================
// Reporter — console summary + GitHub issue body formatter
// ------------------------------------------------------------
// Two output modes:
//   - 'console' — human-readable summary for local CLI runs
//   - 'github'  — markdown body suitable for `gh issue create --body`
// Both modes share the same underlying ChangeReport shape so the
// scheduled CI run can switch modes via env var or CLI flag.
// ============================================================

/**
 * @typedef {Object} ChangeReport
 * @property {string} entryId
 * @property {string} citation
 * @property {string} shortName
 * @property {'unchanged' | 'changed' | 'first-baseline' | 'fetch-error'} status
 * @property {string} [oldHash]
 * @property {string} [newHash]
 * @property {Object} [diff]               from differ.diffBodies
 * @property {string} [tag]                from differ.classifyChange
 * @property {string} sourceUrl
 * @property {string[]} codebaseReferences
 * @property {string} [error]              when status === 'fetch-error'
 */

export function renderConsoleSummary(reports) {
  const lines = ['', '=== CFR Watch Run ===', `Date: ${new Date().toISOString()}`, ''];

  for (const r of reports) {
    const icon = {
      unchanged: '○',
      changed: '●',
      'first-baseline': '◐',
      'fetch-error': '✖',
    }[r.status];
    lines.push(`${icon} ${r.citation} — ${r.shortName}`);
    lines.push(`   Status: ${r.status}`);
    if (r.status === 'changed') {
      lines.push(`   Tag: ${r.tag}`);
      lines.push(`   Diff: +${r.diff.addedCount} / -${r.diff.removedCount} sentences`);
      lines.push(`   Old hash: ${r.oldHash.slice(0, 12)}...`);
      lines.push(`   New hash: ${r.newHash.slice(0, 12)}...`);
    }
    if (r.status === 'fetch-error') {
      lines.push(`   Error: ${r.error}`);
    }
    lines.push('');
  }

  const changedCount = reports.filter(r => r.status === 'changed').length;
  const errorCount = reports.filter(r => r.status === 'fetch-error').length;
  lines.push(`Summary: ${changedCount} changed, ${errorCount} errors, ${reports.length} total`);

  return lines.join('\n');
}

export function renderGithubIssueBody(report) {
  if (report.status !== 'changed') return '';

  return [
    `# CFR change detected: ${report.citation}`,
    '',
    `**Regulation:** ${report.shortName}`,
    `**Triage tag:** \`${report.tag}\``,
    `**Source:** ${report.sourceUrl}`,
    `**Detected:** ${new Date().toISOString()}`,
    '',
    '## Diff summary',
    '',
    `- **Added:** ${report.diff.addedCount} sentences`,
    `- **Removed:** ${report.diff.removedCount} sentences`,
    `- **Total content:** ${report.diff.totalOld} → ${report.diff.totalNew} sentences`,
    '',
    '## Sample changes',
    '',
    '### Added (first 5)',
    '',
    '```',
    report.diff.added.slice(0, 5).join('\n\n') || '(none)',
    '```',
    '',
    '### Removed (first 5)',
    '',
    '```',
    report.diff.removed.slice(0, 5).join('\n\n') || '(none)',
    '```',
    '',
    '## Codebase references',
    '',
    'The following code paths reference this regulation and may need updating:',
    '',
    ...report.codebaseReferences.map(ref => `- ${ref}`),
    '',
    '## Triage routing',
    '',
    triageGuidance(report.tag),
    '',
    '---',
    '',
    `*Generated by [scripts/cfr-watch](../tree/main/scripts/cfr-watch). To re-baseline this entry after review, run \`npm run cfr:baseline -- ${report.entryId}\`.*`,
  ].join('\n');
}

function triageGuidance(tag) {
  switch (tag) {
    case 'code-impact':
      return [
        '**Routes to:** Opus architecture session.',
        '',
        'Change affects encoded business logic (rounding rules, allergen detection, thresholds, mandatory declarations). Codebase update likely required before next deploy. Verify the diff scope, scope the code-fix work, then implement + test + commit per the launch-blocker fix discipline (FDA rounding fix b0919ec is the precedent).',
      ].join('\n');
    case 'interpretation-impact':
      return [
        '**Routes to:** PA (when retained) or operator + Opus.',
        '',
        'Change affects compliance interpretation (disclaimer language, "significant amount" thresholds, guidance updates). May require PA verification on whether the platform\'s current interpretation remains compliant. Pre-launch: operator + Opus triage.',
      ].join('\n');
    case 'no-impact':
      return [
        '**Routes to:** Close as informational.',
        '',
        'Change appears to be formatting / punctuation / non-substantive editorial. Re-baseline the entry to reset the watcher (`npm run cfr:baseline -- <entry-id>`).',
      ].join('\n');
    case 'needs-discussion':
    default:
      return [
        '**Routes to:** Operator + Opus session.',
        '',
        'Change is ambiguous — could be code-impact, interpretation-impact, or no-impact. Surface for review before classifying.',
      ].join('\n');
  }
}
